version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails_blog_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/rails_blog_app_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - rails_storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/rails_blog_app_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - rails_storage:/rails/storage
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  rails_storage:
  redis_data:
